version: '3.9'
services:
  greyeye:
    build: .
    container_name: greyeye-core
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
